sprint-review 20.13
wazo-platform/wazo-platform.org pull request #232
Opened 2020-09-22 14:17 UTC by pc-m

2020-09-22 14:24 UTC, sboily commented
You missed changes in wazo-ui, revamped the menu, add a global settings, add extension member in a group. I think we could talk about the SIP template system which are new.

2020-09-22 14:26 UTC, sboily commented
And also make a warning about major changes on trunk settings and line settings.  I wrote something here https://wazo-platform.discourse.group/t/wazo-20-13-how-trunk-works-now/567

2020-09-22 17:50 UTC, sboily requested changes

2020-09-22 17:50 UTC, sboily commented on content/blog/sprint-review-2013.md
> +done on lines and trunks. https://wazo-platform.discourse.group/t/wazo-20-13-how-trunk-works-now/567
Article is in english not in french.

2020-09-28 17:16 UTC, fblackburn1 approved these changes

2020-09-28 17:50 UTC, merged