pre-dial handlers: add doc for pre-dial handlers
wazo-platform/wazo-platform.org pull request #262
Opened 2021-01-06 18:54 UTC by pc-m

2021-01-12 19:00 UTC, sduthil requested changes

2021-01-12 19:00 UTC, sduthil commented on content/uc-doc/api_sdk/subroutine.md
> +A pre-dial handler is a subroutine that is executed on a channel before it enters it starts ringing.
```suggestion
A pre-dial handler is a subroutine that is executed on the other side of a channel before it starts ringing:  subroutine allows modifying the channel of the caller party, while a pre-dial handler allows modifying the channel of the called party, just before the called party starts to ring.
```

2021-01-12 19:00 UTC, sduthil commented on content/uc-doc/api_sdk/subroutine.md
> +To add this pre-dial handler to an outgoing call create a subroutine
```suggestion
To add this pre-dial handler to an outgoing call, create a subroutine:
```

2021-01-12 19:00 UTC, sduthil commented on content/uc-doc/api_sdk/subroutine.md
> +Finally, you can set the subroutine of you outgoing call to `add-sip-header-pre-dial`.
```suggestion
Finally, you can set the subroutine of your outgoing call to `add-sip-header-pre-dial`.
```

2021-01-13 14:45 UTC, sduthil commented
@pc-m I don't see the suggestions included in your new commit, was that on purpose?

2021-01-13 14:55 UTC, pc-m commented
> @pc-m I don't see the suggestions included in your new commit, was that on purpose?

No, it's not. I made the changes yesterday messed my rebase this morning

2021-01-13 14:58 UTC, pc-m commented
> > @pc-m I don't see the suggestions included in your new commit, was that on purpose?
> 
> No, it's not. I made the changes yesterday messed my rebase this morning

Actually, I think I just skipped this branch :see_no_evil:

2021-01-13 16:14 UTC, sduthil approved these changes

2021-01-13 16:31 UTC, merged