Wazo 2178 sip headers
wazo-platform/wazo-platform.org pull request #263
Opened 2021-01-07 15:40 UTC by pc-m

2021-01-12 19:15 UTC, sduthil approved these changes

2021-01-12 19:15 UTC, sduthil commented on content/uc-doc/administration/interconnections/introduction.md
> +Sometimes it is neccessary to match incoming SIP INVITE against a specific header to route the
```suggestion
Sometimes it is necessary to match incoming SIP INVITE against a specific header to route the
```

2021-01-12 19:15 UTC, sduthil commented on content/uc-doc/administration/interconnections/introduction.md
> +If you provider sends the `X-Dest-User: abc123` header when you receive a call you should add a
```suggestion
If your provider sends the `X-Dest-User: abc123` header when you receive a call you should add a
```

2021-01-12 19:15 UTC, sduthil commented on content/uc-doc/administration/interconnections/introduction.md
> +This is useful in a multi tenant situation where multiple tenants use the same provider.
```suggestion
This is useful in a multi tenant situation where multiple tenants share the same provider.
```

2021-01-12 19:16 UTC, sduthil requested changes
see above comments

2021-01-12 19:27 UTC, pc-m commented
> see above comments

Fixed and rebased thanks

2021-01-13 14:38 UTC, sduthil approved these changes

2021-01-13 22:08 UTC, fblackburn1 commented
@pc-m tag mergeit is missing

2021-01-14 13:24 UTC, merged