Pull request for improve-doc
wazo-platform/wazo-platform.org pull request #344
Opened 2021-05-07 20:04 UTC by fblackburn1

2021-05-07 20:25 UTC, sboily requested changes

2021-05-07 20:25 UTC, sboily commented on content/uc-doc/api_sdk/rest_api/quickstart.md
> +   `https://wazo/api/auth/1.1/api/api.yml` and paste it in your browser.
0.1 for auth api version

2021-05-07 21:23 UTC, fblackburn1 commented on content/uc-doc/api_sdk/rest_api/quickstart.md
> +   `https://wazo/api/auth/1.1/api/api.yml` and paste it in your browser.
Nice catch, fixed

2021-05-10 11:50 UTC, pc-m approved these changes

2021-05-10 12:14 UTC, fblackburn1 commented
regate

2021-05-10 12:28 UTC, merged