add meetings page
wazo-platform/wazo-platform.org pull request #418
Opened 2021-11-04 23:19 UTC by sduthil

2021-11-09 15:26 UTC, fblackburn1 requested changes
Thank you, it's very nice to see this kind of documantion again :smiley: 

I find the usage of `Wazo Platform` painful to read everywhere
I suggest to only use `Wazo` to make difference with external user
Because we are already in the Wazo Platform documentation
or always use `external` when we talk about Ethen or the *other* users

2021-11-10 16:53 UTC, sduthil commented on content/uc-doc/administration/meetings.md
> +join them in a Web conference.
Done, thanks.

2021-11-10 16:53 UTC, sduthil commented on content/uc-doc/administration/meetings.md
> +* A web application for external users (can be the same as for Wazo users)
I added a note that "you should build your own apps" with a link to wazo-webrtc-demo.

2021-11-10 16:55 UTC, sduthil commented on content/uc-doc/administration/meetings.md
> +  ```
No idea if there's a valid syntax highlighter for this, all I know is that this code block is HTTP protocol :)

2021-11-10 21:22 UTC, fblackburn1 submitted a review, later dismissed

2021-11-10 21:22 UTC, fblackburn1 approved these changes

2021-11-10 21:47 UTC, merged