UC DOC - REST API Quickstart improvement
wazo-platform/wazo-platform.org pull request #435
Opened 2021-12-17 21:13 UTC by chartrandf

- Remove gap bellow TOC items
- Move REST API - Quickstart first
- Improve content a bit

2021-12-17 21:53 UTC, fblackburn1 commented on content/uc-doc/api_sdk/rest_api/quickstart.md
> +4. Go to the `POST /tokens` section and click on the yellow box to the right of the `body`
To accept this answer we need to change the previous section that explain how to use the embedded swagger-ui  and add notice that no information will go through our server
The downside with the wazo-platform.org/api is that is not versioned compared to the embedded one

2021-12-20 19:10 UTC, sduthil requested changes

2021-12-20 19:10 UTC, sduthil commented on content/uc-doc/api_sdk/rest_api/quickstart.md
> +5. Now you should see a list of sections for the authentication REST API, like `backends` or `token`
```suggestion
5. Now you should see the documentation for the `wazo-confd` API, and a list of sections for the configuration REST API, like `funckeys` or `users`
```

2021-12-20 19:10 UTC, sduthil commented on content/uc-doc/api_sdk/rest_api/quickstart.md
>  Now that we have an authentication token, we are ready to use the REST API.
We don't have an authentication token at that point.

2021-12-20 19:10 UTC, sduthil commented on content/uc-doc/api_sdk/rest_api/quickstart.md
> +3. In the top-right field, enter your `username:password`  and click to `validate` to obtain a token
```suggestion
3. In the top-right field, enter your `username:password`  and click to `validate` to obtain a temporary token
```

2021-12-20 20:51 UTC, sduthil approved these changes

2021-12-20 21:12 UTC, merged