Update installation documentation
wazo-platform/wazo-platform.org pull request #513
Opened 2022-09-19 21:39 UTC by xxbillouxx

As the installation instructions may be followed by any developer, the documentation has been updated to be more understable.

2022-12-22 17:08 UTC, bloom1 commented
@xxbillouxx the prettier is failing
You can fix it by running `yarn format:uc-doc`

2022-12-22 19:11 UTC, fblackburn1 requested changes
Oh I missed it.
We cannot write this. It's kind of major security issue to use root password to use API
we need to use `api_client_name` and `api_client_password`
If it wasn't clear, maybe an optional step that show how to configure them (via ansible variable) can be added

2023-08-09 19:34 UTC, sduthil commented
This PR is all nice, except for the hardcoded `root` part. @xxbillouxx should we revert the hardcoded root or add an extra step to create a dedicated API user?

2024-03-21 11:07 UTC, fblackburn1 approved these changes

2024-03-21 11:33 UTC, merged