Add typing to style guide and update a few examples
wazo-platform/wazo-platform.org pull request #563
Opened 2023-01-13 20:25 UTC by sopelj

2023-01-13 20:40 UTC, fblackburn1 reviewed
Nice example
About the refactoring/styling part, what do you thing about removing good/bad practice already handled by our linters? Is it worth keeping them here?

2023-01-13 20:45 UTC, sopelj commented
> Nice example About the refactoring/styling part, what do you thing about removing good/bad practice already handled by our linters? Is it worth keeping them here?

Thanks! Yeah, good point. I'm up for removing things. Did you have some in mind? Black is very opinionated it covers a few of them. It also covers a bunch of things we don't mention. We could always point people to black or pep8 for more info for some points

2023-01-13 20:54 UTC, fblackburn1 commented
> > Nice example About the refactoring/styling part, what do you thing about removing good/bad practice already handled by our linters? Is it worth keeping them here?
> 
> Thanks! Yeah, good point. I'm up for removing things. Did you have some in mind? Black is very opinionated it covers a few of them. It also covers a bunch of things we don't mention. We could always point people to black or pep8 for more info for some points

:+1: for everything, if you want to point black/pep8 too
I don't have specific item in mind. I just know that these examples are here long time before we got linters

2023-01-13 21:16 UTC, sopelj commented
> > > Nice example About the refactoring/styling part, what do you thing about removing good/bad practice already handled by our linters? Is it worth keeping them here?
> > 
> > 
> > Thanks! Yeah, good point. I'm up for removing things. Did you have some in mind? Black is very opinionated it covers a few of them. It also covers a bunch of things we don't mention. We could always point people to black or pep8 for more info for some points
> 
> +1 for everything, if you want to point black/pep8 too I don't have specific item in mind. I just know that these examples are here long time before we got linters and CI inside PR

Ok, thanks! I added a section about linters with both tox and pre-commit and removed the examples with backslashes and redundant parentheses as they are covered by black.

2023-01-16 14:21 UTC, fblackburn1 commented
LGTM, I'll like a quick review of @DrPyser if there is something missing or to be improved

2023-01-17 15:26 UTC, fblackburn1 commented
LGTM

2023-01-17 16:02 UTC, DrPyser requested changes

2023-01-17 16:32 UTC, sopelj commented on content/uc-doc/contributors/typing.md
> +This allows you to for example:
Missing a comma, but this is perfectly valid :P

2023-01-17 16:38 UTC, sopelj commented on content/uc-doc/contributors/style_guide.md
> +(after `pre-commit install` in your repo), manually with `pre-commit run --all-files` or via tox
I didn't put mypy after since there is no equivalent for tox. It is run via linters with all the others.

2023-01-17 16:40 UTC, sopelj commented on content/uc-doc/contributors/style_guide.md
> +UserData = TypedDict('UserData', {'first_name': str, 'last_name': str, 'email': Union[str, None]})
It's still quite readable, but it was mostly to avoid huge blocks in the if type checking. Just trying to be concise.

2023-01-17 16:42 UTC, sopelj commented on content/uc-doc/contributors/style_guide.md
> +UserData = TypedDict('UserData', {'first_name': str, 'last_name': str, 'email': Union[str, None]})
Also the `|` syntax doesn't work for assignment as is uses them to construct the dict.

2023-01-17 16:44 UTC, sopelj commented on content/uc-doc/contributors/style_guide.md
> +To try and maintain a clean and consistent code base we use `black` which is a tool that enforces a
I think it's clear that black is a tool from context. Also, it is not only for style. Ity enforces consistent code. :)

2023-01-17 16:53 UTC, sopelj commented on content/uc-doc/contributors/typing.md
> +Here are some examples and basics on typing. More information on the why and how to run type
It would be "basic typing principles" if you wanted to say it that way, but I don't think it's required.

2023-01-17 16:56 UTC, sopelj commented on content/uc-doc/contributors/typing.md
> +expect specific strings like `'on'` or `'off'`. The standard library uses this for read/write modes
They are quite different than Enum classes. They are simply distinct string values. Not sure of the link here

2023-01-17 16:57 UTC, sopelj commented on content/uc-doc/contributors/typing.md
> +interface.
No, it's singular

2023-01-17 17:01 UTC, sopelj commented on content/uc-doc/contributors/typing.md
> +workflow, and it is run in our CI.
It is not just consistent, it is literally run.

2023-01-17 21:24 UTC, DrPyser approved these changes

2023-01-17 21:38 UTC, merged