Sprint review blog post for 24.04
wazo-platform/wazo-platform.org pull request #694
Opened 2024-03-18 12:44 UTC by ja0x

2024-03-18 12:54 UTC, sboily commented
wazo-ui has been translated in french and now we support only French and English.

2024-03-18 15:00 UTC, ja0x commented
I'll add it to blog post

2024-03-19 14:47 UTC, sduthil requested changes

2024-03-19 14:50 UTC, pc-m approved these changes

2024-03-19 14:59 UTC, merged