Sync content from docusaurus to gastby
wazo-platform/wazo-platform.org pull request #761
Opened 2024-09-25 16:07 UTC by chartrandf

## Context

Avoid content duplication between beta.wazo-platform.org and live website (Gatsby).

## Summary of change

Do not allow files in `content/blog` (Gastby) but only sync them from Docusaurus. Until the new website is ready, this will make us maintaining one place for contents.

- Delete / ignore all files inside `content/blog`
- Scripts that sync content and make them valid for Gastby website

2024-09-25 17:14 UTC, Romej reviewed
Doing manual tests

2024-09-25 17:14 UTC, Romej commented on website/release-notes/sprint-review-2402.md
new empty file ?

2024-09-25 17:14 UTC, Romej commented on website/release-notes/sprint-review-2403.md
new empty file ?

2024-09-25 17:30 UTC, Romej requested changes
Suggested change so that it works on Linux too

2024-09-25 17:30 UTC, Romej commented on scripts/beta-sync.sh
> +# Goal: Temporary script that copy beta content to old website until migration will be done
```suggestion
#!/bin/bash
# Goal: Temporary script that copy beta content to old website until migration will be done
```

2024-09-25 17:30 UTC, Romej commented on scripts/beta-sync.sh
> +sed -i '' 's/..\/static/https:\/\/beta.wazo-platform.org\//g' content/blog/*.md # image source
```suggestion
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sed_cmd="sed -i ''"
else
    # Linux
    sed_cmd="sed -i"
fi

# Modify tags format
$sed_cmd 's/tags: \[\(.*\)\]/tags: \1/g' content/blog/*.md
# Update image source URLs
$sed_cmd 's|../static|https://beta.wazo-platform.org/|g' content/blog/*.md
```

2024-09-25 17:39 UTC, Romej reviewed
`src/component/blog/article.js` seems to be missing the `author` : 

![image](https://github.com/user-attachments/assets/e02dc811-2b45-44a8-9249-73c23b019bef)

2024-09-25 19:33 UTC, chartrandf commented on website/release-notes/sprint-review-2402.md
Permissions change, was having execute mode.

2024-09-26 18:47 UTC, Romej approved these changes

2024-09-26 18:47 UTC, merged